language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
php:
    - 5.6
    - 7.1
    - 7.2

matrix:
    fast_finish: true

before_script:
    - composer self-update

install:
    - composer install

script:
    - bin/phpspec run
